### ISSUE TITLE
Incorrect error type for websocket and card response objects

### ISSUE THREAD

**Issue by zcyllainowu** [CardScan-ai/api-clients#36]
Websocket event objects have an incorrectly typed `error` field. The current type is:

```yaml
    ApiErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: A message describing the error.
        type:
          type: string
          description: The type of error.
        code:
          type: number
          description: The error code.
```

And the actual type of the error is (incorrect type for `code` field):
```jsonc
{
    //...
    "error": {
        "type": "ImageError",
        "message": "Skipping file with no numbers",
        "code": "UKN",
        "error": "ImageError"
    },
    //...
}
```
 
The `ApiErrorResponse` component is incorrectly used for the websocket event object
